/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Livro;
/**
 *
 * @author wagner
 */
public class BuscaLivros extends javax.swing.JFrame {

    /**
     * Creates new form BuscaLivros
     */
    public BuscaLivros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_Codigo = new javax.swing.JLabel();
        jtf_Codigo = new javax.swing.JTextField();
        jbt_buscarLivros = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfa_Area = new javax.swing.JTextArea();
        jrb_BuscarTodos = new javax.swing.JRadioButton();
        jbt_Editar = new javax.swing.JButton();
        jbt_Excluir = new javax.swing.JButton();
        jbt_Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Livros em Acervo");

        jlb_Codigo.setText("Código:");

        jtf_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_CodigoActionPerformed(evt);
            }
        });

        jbt_buscarLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icBuscar.png"))); // NOI18N
        jbt_buscarLivros.setText("Buscar Livro");
        jbt_buscarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_buscarLivrosActionPerformed(evt);
            }
        });

        jtfa_Area.setColumns(20);
        jtfa_Area.setRows(5);
        jScrollPane1.setViewportView(jtfa_Area);

        jrb_BuscarTodos.setText("Buscar Todos");
        jrb_BuscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_BuscarTodosActionPerformed(evt);
            }
        });

        jbt_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icAtualizar.png"))); // NOI18N
        jbt_Editar.setText("Editar");

        jbt_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icExcluir.png"))); // NOI18N
        jbt_Excluir.setText("Excluir");

        jbt_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icSair.png"))); // NOI18N
        jbt_Sair.setText("Sair");
        jbt_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlb_Codigo)
                    .addComponent(jtf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jbt_buscarLivros)
                .addGap(76, 76, 76)
                .addComponent(jrb_BuscarTodos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jbt_Editar)
                .addGap(125, 125, 125)
                .addComponent(jbt_Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbt_Sair)
                .addGap(127, 127, 127))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbt_buscarLivros)
                        .addComponent(jrb_BuscarTodos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlb_Codigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_Excluir)
                    .addComponent(jbt_Sair)
                    .addComponent(jbt_Editar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_CodigoActionPerformed

    private void jbt_buscarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_buscarLivrosActionPerformed
        // TODO add your handling code here:
        jtf_Codigo.setText("");// limpando a area de texto sempre
        if(jrb_BuscarTodos.isSelected()) // verifica se a opçao de todos esta setada
        {
            List<Livro> cad = new ArrayList<Livro>();
            cad = formPrincipal.daoLivro.todosLivros(); //pego a lista de todos no dao
            for(Livro livro: cad)
            {
                jtfa_Area.append(livro.toString()); 
            }
        }
        else
        {
            if(jtf_Codigo.getText().trim().length() != 0)
            {
                int codigo = Integer.parseInt(jtf_Codigo.getText());
                Livro livro = formPrincipal.daoLivro.buscarLivro(codigo);
                if(livro != null)
                {   
                    jtf_Codigo.setText(livro.toString());
                }
                else
                    JOptionPane.showMessageDialog(null, "Livro não encontrado!", "Atenção!", JOptionPane.ERROR_MESSAGE);
                
            }
              else
            {
                JOptionPane.showMessageDialog(null, "Favor preencher o Código do Livro!", "Atenção!", JOptionPane.ERROR_MESSAGE);
                jtf_Codigo.requestFocus();
            }
        }
    }//GEN-LAST:event_jbt_buscarLivrosActionPerformed

    private void jrb_BuscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_BuscarTodosActionPerformed
        // TODO add your handling code here:
        if(jrb_BuscarTodos.isSelected())
            jtf_Codigo.setEnabled(false);
        else
        {
            jtf_Codigo.setEnabled(true);
            jtf_Codigo.requestFocus();
        }
        jtf_Codigo.setText("");
    }//GEN-LAST:event_jrb_BuscarTodosActionPerformed

    private void jbt_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_SairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbt_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscaLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_Editar;
    private javax.swing.JButton jbt_Excluir;
    private javax.swing.JButton jbt_Sair;
    private javax.swing.JButton jbt_buscarLivros;
    private javax.swing.JLabel jlb_Codigo;
    private javax.swing.JRadioButton jrb_BuscarTodos;
    private javax.swing.JTextField jtf_Codigo;
    private javax.swing.JTextArea jtfa_Area;
    // End of variables declaration//GEN-END:variables
}
