/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import javax.swing.JOptionPane;
import model.Livro;

/**
 *
 * @author wagner
 */
public class CadastroLivors extends javax.swing.JFrame {

    /**
     * Creates new form CadastroLivors
     */
    public CadastroLivors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        jbtn_Cadastrar = new javax.swing.JButton();
        jbtn_Atualizar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jbtn_Cancelar = new javax.swing.JButton();
        jbtn_Sair = new javax.swing.JButton();
        jlb_Codigo = new javax.swing.JLabel();
        jftxf_Codigo = new javax.swing.JFormattedTextField();
        jlb_Titulo = new javax.swing.JLabel();
        jtf_Titulo = new javax.swing.JTextField();
        jlb_Fornecedor = new javax.swing.JLabel();
        jcb_fornecedor = new javax.swing.JComboBox<>();
        jlb_ValorUni = new javax.swing.JLabel();
        jlb_QuantiEsto = new javax.swing.JLabel();
        jlb_DataPubl = new javax.swing.JLabel();
        jtf_ValorUni = new javax.swing.JTextField();
        jtf_QuantiEsto = new javax.swing.JTextField();
        jFtxf_DataPubli = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de livros (Acervo)");

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jbtn_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icCadlivro.png"))); // NOI18N
        jbtn_Cadastrar.setText("Cadastrar");
        jbtn_Cadastrar.setFocusable(false);
        jbtn_Cadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_Cadastrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CadastrarActionPerformed(evt);
            }
        });
        jToolBar2.add(jbtn_Cadastrar);

        jbtn_Atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icAtualizar.png"))); // NOI18N
        jbtn_Atualizar.setText("Atualizar");
        jbtn_Atualizar.setFocusable(false);
        jbtn_Atualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_Atualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jbtn_Atualizar);
        jToolBar2.add(jSeparator1);

        jbtn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icCancelar.png"))); // NOI18N
        jbtn_Cancelar.setText("Cancelar");
        jbtn_Cancelar.setFocusable(false);
        jbtn_Cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_Cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jbtn_Cancelar);

        jbtn_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icSair.png"))); // NOI18N
        jbtn_Sair.setText("Sair");
        jbtn_Sair.setFocusable(false);
        jbtn_Sair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_Sair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jbtn_Sair);

        jlb_Codigo.setText("Código:");

        jlb_Titulo.setText("Titulo:");

        jlb_Fornecedor.setText("Fornecedor:");

        jcb_fornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editora Melhoramentos", "Editora SuperLancamentos", "Editora Sonhos", "Editora Arcoiris" }));

        jlb_ValorUni.setText("Valor unitário:");

        jlb_QuantiEsto.setText("Quantidade em Estoque:");

        jlb_DataPubl.setText("Data de Publicação:");

        jtf_ValorUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_ValorUniActionPerformed(evt);
            }
        });

        jtf_QuantiEsto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_QuantiEstoActionPerformed(evt);
            }
        });

        try {
            jFtxf_DataPubli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFtxf_DataPubli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFtxf_DataPubliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_ValorUni)
                            .addComponent(jtf_ValorUni, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlb_QuantiEsto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_QuantiEsto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlb_DataPubl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFtxf_DataPubli)))
                    .addComponent(jcb_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftxf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_Codigo)
                            .addComponent(jlb_Fornecedor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_Titulo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_Codigo)
                    .addComponent(jlb_Titulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftxf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jlb_Fornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_ValorUni)
                    .addComponent(jlb_QuantiEsto)
                    .addComponent(jlb_DataPubl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_ValorUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_QuantiEsto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFtxf_DataPubli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_ValorUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_ValorUniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_ValorUniActionPerformed

    private void jtf_QuantiEstoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_QuantiEstoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_QuantiEstoActionPerformed

    private void jFtxf_DataPubliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFtxf_DataPubliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFtxf_DataPubliActionPerformed

    private void jbtn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CadastrarActionPerformed
        // TODO add your handling code here:
           int op = JOptionPane.showConfirmDialog(null, "Deseja inserir multiplos Livros?", "Cadastro de Livros", JOptionPane.YES_NO_OPTION);
        if(op == JOptionPane.YES_OPTION)
        {
            this.cadastrarLivros(); // inserindo vários livros na base de dados
            JOptionPane.showMessageDialog(null, "Livros inseridos com sucesso!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbtn_CadastrarActionPerformed

    
     public void cadastrarLivros()
    {
        Livro livro = null; //criando um livro
        for(int i=1; i<30; i++) // serão acrescentados 30 livros na base
        {
            livro = new Livro();        // livro iniciado            
            livro.setCodigo(1000+i); // codigo do livro sendo incrementado em sequencialmente pelo for
            livro.setTitulo("Livro com Titulo " + i); // incrementando o titulo do livro pelo for
            livro.setFornecedor("Editora " + i+10); // 
            livro.setQuantidadeEst((int)(Math.random() * 10)+ 10*i);
            livro.setValorUnitario((50%i) + (i*10));            
            livro.setData(i+"/05/"+(1990+i));
            formPrincipal.daoLivro.inserirLivro(livro); //adicionando um livro genérico na base
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLivors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLivors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLivors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLivors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLivors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFtxf_DataPubli;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton jbtn_Atualizar;
    private javax.swing.JButton jbtn_Cadastrar;
    private javax.swing.JButton jbtn_Cancelar;
    private javax.swing.JButton jbtn_Sair;
    private javax.swing.JComboBox<String> jcb_fornecedor;
    private javax.swing.JFormattedTextField jftxf_Codigo;
    private javax.swing.JLabel jlb_Codigo;
    private javax.swing.JLabel jlb_DataPubl;
    private javax.swing.JLabel jlb_Fornecedor;
    private javax.swing.JLabel jlb_QuantiEsto;
    private javax.swing.JLabel jlb_Titulo;
    private javax.swing.JLabel jlb_ValorUni;
    private javax.swing.JTextField jtf_QuantiEsto;
    private javax.swing.JTextField jtf_Titulo;
    private javax.swing.JTextField jtf_ValorUni;
    // End of variables declaration//GEN-END:variables
}
