/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import dao.ClienteDao;
import java.awt.Toolkit;

/**
 *
 * @author alunoces
 */
public class formPrincipal extends javax.swing.JFrame {

    public static ClienteDao bdcliente = null;
    /**
     * Creates new form formPrincipal
     */
    public formPrincipal() {
        bdcliente = new ClienteDao(); // base de dados do cliente estou iniciando os dados do clientes
        initComponents();
        //this.setExtendedState(this.MAXIMIZED_BOTH);
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Cadastros = new javax.swing.JMenu();
        jMenuItem_Clientes = new javax.swing.JMenuItem();
        jMenuItem_Produto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Sair = new javax.swing.JMenuItem();
        jMenu_Consulta = new javax.swing.JMenu();
        jMenuItem1_Clientes = new javax.swing.JMenuItem();
        jMenuItem1_Produtos = new javax.swing.JMenuItem();
        jMenu1_Compas = new javax.swing.JMenu();
        jMenuItem1_Compras_Dia = new javax.swing.JMenuItem();
        jMenuItem1_Compras_Mes = new javax.swing.JMenuItem();
        jMenuItem1_Compras_Ano = new javax.swing.JMenuItem();
        jMenu1_Vendas = new javax.swing.JMenu();
        jMenuItem_NovaVenda = new javax.swing.JMenuItem();
        jMenuItem1_Emitir_NF = new javax.swing.JMenuItem();
        jMenu1_Suporte = new javax.swing.JMenu();
        jMenuItem1_Ajuda = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1_Sobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle da Livraria Livro Aberto");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenu_Cadastros.setText("Cadastro");
        jMenu_Cadastros.setName(""); // NOI18N

        jMenuItem_Clientes.setText("Clientes");
        jMenu_Cadastros.add(jMenuItem_Clientes);

        jMenuItem_Produto.setText("Produto");
        jMenuItem_Produto.setToolTipText("");
        jMenuItem_Produto.setName(""); // NOI18N
        jMenu_Cadastros.add(jMenuItem_Produto);
        jMenu_Cadastros.add(jSeparator1);

        jMenuItem_Sair.setText("Sair");
        jMenu_Cadastros.add(jMenuItem_Sair);

        jMenuBar1.add(jMenu_Cadastros);

        jMenu_Consulta.setText("Consultas");
        jMenu_Consulta.setToolTipText("");
        jMenu_Consulta.setName(""); // NOI18N

        jMenuItem1_Clientes.setText("Clientes");
        jMenu_Consulta.add(jMenuItem1_Clientes);

        jMenuItem1_Produtos.setText("Produtos");
        jMenu_Consulta.add(jMenuItem1_Produtos);

        jMenu1_Compas.setText("Compras");

        jMenuItem1_Compras_Dia.setText("Dia");
        jMenu1_Compas.add(jMenuItem1_Compras_Dia);

        jMenuItem1_Compras_Mes.setText("Mes");
        jMenu1_Compas.add(jMenuItem1_Compras_Mes);

        jMenuItem1_Compras_Ano.setText("Ano");
        jMenu1_Compas.add(jMenuItem1_Compras_Ano);

        jMenu_Consulta.add(jMenu1_Compas);

        jMenuBar1.add(jMenu_Consulta);

        jMenu1_Vendas.setText("Vendas");
        jMenu1_Vendas.setToolTipText("");

        jMenuItem_NovaVenda.setText("Nova Venda");
        jMenu1_Vendas.add(jMenuItem_NovaVenda);

        jMenuItem1_Emitir_NF.setText("Emitir N.F");
        jMenu1_Vendas.add(jMenuItem1_Emitir_NF);

        jMenuBar1.add(jMenu1_Vendas);

        jMenu1_Suporte.setText("Suporte");

        jMenuItem1_Ajuda.setText("Ajuda");
        jMenu1_Suporte.add(jMenuItem1_Ajuda);
        jMenu1_Suporte.add(jSeparator2);

        jMenuItem1_Sobre.setText("Sobre");
        jMenu1_Suporte.add(jMenuItem1_Sobre);

        jMenuBar1.add(jMenu1_Suporte);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 774, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       //this.setMaximizedBounds(this.MAXIMIZED_BOTH);
       //this.setState(this.MAXIMIZED_BOTH);
       this.setSize(Toolkit.getDefaultToolkit().getScreenSize()); // funçao para maximizar a tela !!! no linux ou resolução difetentes!!!
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPrincipal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1_Compas;
    private javax.swing.JMenu jMenu1_Suporte;
    private javax.swing.JMenu jMenu1_Vendas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1_Ajuda;
    private javax.swing.JMenuItem jMenuItem1_Clientes;
    private javax.swing.JMenuItem jMenuItem1_Compras_Ano;
    private javax.swing.JMenuItem jMenuItem1_Compras_Dia;
    private javax.swing.JMenuItem jMenuItem1_Compras_Mes;
    private javax.swing.JMenuItem jMenuItem1_Emitir_NF;
    private javax.swing.JMenuItem jMenuItem1_Produtos;
    private javax.swing.JMenuItem jMenuItem1_Sobre;
    private javax.swing.JMenuItem jMenuItem_Clientes;
    private javax.swing.JMenuItem jMenuItem_NovaVenda;
    private javax.swing.JMenuItem jMenuItem_Produto;
    private javax.swing.JMenuItem jMenuItem_Sair;
    private javax.swing.JMenu jMenu_Cadastros;
    private javax.swing.JMenu jMenu_Consulta;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
